## @section Global parameters
global:
  ## @param global.imageRegistry Global Docker Image registry
  imageRegistry: ""
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  imagePullSecrets: []

## @section Common parameters
## @param nameOverride String to partially override sonarr.fullname
nameOverride: ""
## @param fullnameOverride String to fully override sonarr.fullname
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
commonAnnotations: {}

## @section sonarr image parameters
image:
  ## @param image.registry sonarr image registry
  registry: docker.io
  ## @param image.repository sonarr image repository
  repository: linuxserver/sonarr
  ## @param image.tag sonarr image tag (immutable tags are recommended)
  tag: "latest"
  ## @param image.pullPolicy sonarr image pull policy
  imagePullPolicy: Always

## @section Sonarr Authentication parameters
auth:
  ## @param create service account for Sonarr
  saEnabled: true
  ## @param auth.authenticationMethod NZBGet (Forms or External) (Use External to reset the Passwort or for first start)
  authenticationMethod: Forms
  ## @param auth.AuthenticationRequired Enable or disable authentication
  AuthenticationRequired: Enabled
  ## @param auth.apiKey NZBGet API key (4f2c460385004d6594414e3442j54c79)
  apiKey: ""
  ## @param auth.existingSecret Name of existing secret to use for NZBGet api key
  existingSecret:
    ## @param auth.existingSecret.secretName Name of the existing secret
    secretName: ""
    ## @param auth.existingSecret.secretKey Key in the existing secret that contains the api key
    secretKey: ""

## @section Sonarr configuration parameters
config:
  ## @param config.logLevel Sonarr log level (trace, debug, info, warn, error, fatal)
  logLevel: debug

## @section sonarr service parameters
service:
  ## @param service.type sonarr service type
  type: ClusterIP
  ## @param service.port sonarr service port
  port: 8989
  ## @param service.nodePort Node port for sonarr service
  nodePort: ""
  ## @param service.clusterIP Static cluster IP or "None" for headless service
  clusterIP: ""
  ## @param service.annotations Additional custom annotations for sonarr service
  annotations: {}

## @section Persistence parameters
persistence:
  ## @param persistence.enabled Enable sonarr data persistence using PVC
  enabled: true
  ## @param persistence.storageClass PVC Storage Class for sonarr data volume
  storageClass: ""
  ## @param persistence.accessModes PVC Access modes
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size PVC Storage Request for sonarr data volume
  size: 2Gi
  ## @param persistence.annotations Additional custom annotations for the PVC
  annotations: {}
  ## @param persistence.selector Additional labels for the PVC
  selector: {}

## @section Pod Security Context
podSecurityContext:
  ## @param podSecurityContext.enabled Enable sonarr pod Security Context
  enabled: true
  ## @param podSecurityContext.fsGroup Set sonarr pod's Security Context fsGroup
  fsGroup: 1000

## @section Container Security Context
containerSecurityContext:
  ## @param containerSecurityContext.runAsUser Set sonarr container's Security Context runAsUser
  runAsUser: 1000
  ## @param containerSecurityContext.runAsGroup Set sonarr container's Security Context runAsGroup
  runAsGroup: 1000
  ## @param containerSecurityContext.runAsNonRoot Set sonarr container's Security Context runAsNonRoot
  runAsNonRoot: true
  ## @param containerSecurityContext.allowPrivilegeEscalation Set sonarr container's privilege escalation
  allowPrivilegeEscalation: true

## @section Resources parameters
resources: {}
  ## @param resources.limits The resources limits for the sonarr containers
  ## limits:
  ##   memory: 300Mi
  ## @param resources.requests The requested resources for the sonarr containers
  ## requests:
  ##   memory: 300Mi
  ##   cpu: 100m

## @section Extra Configs
## @param env A list of additional environment Variables
env:
  - name: TZ
    value: "Europe/Zurich"
## @param extraSecrets A list of additional existing secrets that will be mounted into the container
extraSecrets: []
##  - name: secret
##    defaultMode: 0440
##    mountPath: /mnt/secret
## @param extraConfigs A list of additional existing configMaps that will be mounted into the container
extraVolumes: []
##  - name: volume
##    mountPath: /mnt/tmp
##    pvcName: pvc-001
nfsVolumes: []
##  - name: plex-media
##    mountPath: /downloads
##    nfs:
##      server: 192.168.x.x
##      path: /downloads

## @section sonarr container's liveness probe parameters
livenessProbe:
  ## @param livenessProbe.enabled Enable livenessProbe on MariaDB containers
  enabled: true
  ## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  initialDelaySeconds: 30
  ## @param livenessProbe.periodSeconds Period seconds for livenessProbe
  periodSeconds: 10
  ## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  timeoutSeconds: 1
  ## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
  failureThreshold: 3
  ## @param livenessProbe.successThreshold Success threshold for livenessProbe
  successThreshold: 1

## @section sonarr container's readiness probe parameters
readinessProbe:
  ## @param readinessProbe.enabled Enable readinessProbe on MariaDB containers
  enabled: true
  ## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  initialDelaySeconds: 5
  ## @param readinessProbe.periodSeconds Period seconds for readinessProbe
  periodSeconds: 10
  ## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  timeoutSeconds: 1
  ## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
  failureThreshold: 3
  ## @param readinessProbe.successThreshold Success threshold for readinessProbe
  successThreshold: 1

## @section sonarr container's startup probe parameters
startupProbe:
  ## @param startupProbe.enabled Enable startupProbe on MariaDB containers
  enabled: false
  ## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  initialDelaySeconds: 30
  ## @param startupProbe.periodSeconds Period seconds for startupProbe
  periodSeconds: 10
  ## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
  timeoutSeconds: 1
  ## @param startupProbe.failureThreshold Failure threshold for startupProbe
  failureThreshold: 15
  ## @param startupProbe.successThreshold Success threshold for startupProbe
  successThreshold: 1

## @section Ingress parameters
ingress:
  ## @param ingress.enabled Enable ingress record generation for sonarr
  enabled: false
  ## @param ingress.className IngressClass that will be used to implement the Ingress (Kubernetes 1.18+)
  className: ""
  ## @param ingress.annotations Additional annotations for the Ingress resource
  annotations:
    kubernetes.io/hostname: sonarr.local
  ## @param ingress.hosts An array with hosts and paths
  hosts:
    - host: sonarr.local
      paths:
        - path: /
          pathType: Prefix
  ## @param ingress.tls TLS configuration for the Ingress
  tls: []

## @section Network Policy configuration
networkPolicy:
  ## @param networkPolicy.enabled Specifies whether a NetworkPolicy should be created
  enabled: false
  ## @param networkPolicy.allowExternal Don't require client label for connections
  allowExternal: true
  ## @param networkPolicy.ingressNSMatchLabels Labels to match to allow traffic from other namespaces
  ingressNSMatchLabels: {}
  ## @param networkPolicy.ingressNSPodMatchLabels Pod labels to match to allow traffic from other namespaces
  ingressNSPodMatchLabels: {}
  
  destinations:
    nzbget:
      Port: 6789
      selectorLabels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/instance: nzbget

metrics:
  ## @param metrics.enabled Enable the sonarr metrics exporter deployment
  enabled: false
  image:
    ## @param metrics.image Docker image for the sonarr metrics exporter
    registry: ghcr.io
    repository: onedr0p/exportarr
    tag: v2.3 # https://github.com/onedr0p/exportarr/pkgs/container/exportarr
    imagePullPolicy: IfNotPresent
  serviceMonitor:
    ## @param metrics.service.enabled Create a ServiceMonitor for the sonarr metrics exporter
    enabled: false
    ## @param metrics.service.port Port the ServiceMonitor should scrape
    interval: 4m
    ## @param metrics.service.scrapeTimeout Scrape timeout for the ServiceMonitor
    scrapeTimeout: 90s
    ## @param metrics.service.labels Additional labels for the ServiceMonitor
    labels: {}
    ## @param metrics.service.metricRelabelings Metric relabelings for the ServiceMonitor
    metricRelabelings: []
    ## @param metrics.service.relabelings Relabelings for the ServiceMonitor
    relabelings: []
  service:
    ## @param metrics.service.port Port the sonarr metrics exporter listens on
    port: 9707
    ## @param metrics.service.interval Scrape interval for the sonarr metrics exporter
    annotations: {}
  ## @param metrics.containerPort Port the sonarr metrics exporter container listens on
  containerPort: 9707
  resources: {}
    ## @param metrics.resources.limits The resources limits for the sonarr metrics exporter container
    ## limits:
    ##   cpu: 500m
    ##   memory: 256Mi
    ## @param metrics.resources.requests The requested resources for the sonarr metrics exporter container
    ## requests:
    ##   memory: 64Mi
    ##   cpu: 100m

## @section Pod configuration
podAnnotations: {}
podLabels: {}
nodeSelector: {}
tolerations: []
affinity: {}

## @param extraObjects Array of extra objects to deploy with the release
extraObjects: []
