{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nzbget.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nzbget.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.allowExternal }}
  ingress:
    - {}
  {{- else }}
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  {{- end }}
  egress:
    - {}
{{- end }}
