{{- if and .Values.auth.createSecret (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nzbget.fullname" . }}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ include "chrt-6456.password" . | b64enc | quote }}
{{- end -}}
