{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sonarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.allowExternal }}
  ingress:
    - {}
  {{- else }}
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{ .Values.networkPolicy.destinations.nzbget.selectorLabels | toYaml | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.destinations.nzbget.Port }}
{{- end }}
