apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "bazarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bazarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
{{- with (include "bazarr.imagePullSecrets" .) }}
{{- . | nindent 6 }}
{{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.podSecurityContext.fsGroupChangePolicy }}
      {{- end }}
      {{- if .Values.config.saEnabled }}
      serviceAccountName: {{ include "bazarr.fullname" . }}-sa
      {{- end }}
      initContainers:
        - name: copy-bazarr-config
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: busybox
          env:
            - name: PUID
              value: {{ .Values.containerSecurityContext.runAsUser | default 1000 | quote }}
            - name: PGID
              value: {{ .Values.containerSecurityContext.runAsGroup | default 1000 | quote }}
          command:
            - sh
            - -c
            - >
                echo "PUID=$PUID, PGID=$PGID" &&
                mkdir -p /config/config &&
                cp -v /temp/config.yaml /config/config/config.yaml &&
                chown "${PUID}:${PGID}" /config/config/config.yaml &&
                chmod 664 /config/config/config.yaml &&
                ls -l /config/config
          volumeMounts:
            {{- if or (.Values.config.existingConfigMap) (.Values.config.existingSecret) (.Values.config.useExternalSecret) }}
            - name: bazarr-temp-config
              mountPath: /temp/config.yaml
              subPath: config.yaml
            {{- end }}
            - name: config
              mountPath: /config
            {{- if .Values.extraVolumes }}
            {{- range $storage := .Values.extraVolumes }}
            - name: {{ $storage.name }}
              mountPath: {{ $storage.mountPath }}
            {{- end }}
            {{- end }}
      containers:
        - name: bazarr
          image: {{ include "bazarr.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
            {{- if .Values.containerSecurityContext.runAsUser }}
            - name: PUID
              value: {{ .Values.containerSecurityContext.runAsUser | quote }}
            {{- end }}
            {{- if .Values.containerSecurityContext.runAsGroup }}
            - name: PGID
              value: {{ .Values.containerSecurityContext.runAsGroup | quote }}
            {{- end }}
          ports:
            - name: bazarr-http
              containerPort: {{ .Values.service.port | default 6767 }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- $probe := merge (omit .Values.livenessProbe "enabled") (dict "httpGet" (dict "port" (.Values.service.port | default 6767) "path" "/ping")) }}
            {{- $probe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- $probe := merge (omit .Values.readinessProbe "enabled") (dict "httpGet" (dict "port" (.Values.service.port | default 6767) "path" "/ping")) }}
            {{- $probe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- $probe := merge (omit .Values.startupProbe "enabled") (dict "httpGet" (dict "port" (.Values.service.port | default 6767) "path" "/ping")) }}
            {{- $probe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.extraVolumes }}
            {{- range $storage := .Values.extraVolumes }}
            - name: {{ $storage.name }}
              mountPath: {{ $storage.mountPath }}
            {{- end }}
            {{- end }}
            {{- if .Values.nfsVolumes }}
            {{- range $nfsstorage := .Values.nfsVolumes }}
            - name: {{ $nfsstorage.name }}
              mountPath: {{ $nfsstorage.mountPath }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraConfigMaps }}
            {{- range $configMap := .Values.extraConfigMaps }}
            - name: {{ $configMap.name }}
              mountPath: {{ $configMap.mountPath }}
              subPath: {{ $configMap.subPath }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraSecrets }}
            {{- range $secret := .Values.extraSecrets }}
            - name: {{ $secret.name }}
              mountPath: {{ $secret.mountPath }}
              subPath: {{ $secret.subPath }}
            {{- end }}
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ .Values.metrics.image.registry }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          imagePullPolicy: {{ .Values.metrics.image.imagePullPolicy }}
          args:
            - bazarr
            {{- range .Values.metrics.extraArgs }}
            {{- if not (hasPrefix "--" .) }}
            - {{ . }}
            {{- end }}
            {{- end }}
          env:
            - name: PORT
              value: {{ .Values.metrics.containerPort | default 9707 | quote }}
            - name: URL
              value: "http://localhost:{{ .Values.service.port | default 6767 }}"
            {{- if and .Values.auth.apiKey (not .Values.auth.existingSecret) }}
            - name: APIKEY
              value: {{ .Values.auth.apiKey | quote }}
            {{- else if and .Values.metrics.auth.existingSecret.secretName .Values.metrics.auth.existingSecret.secretKey }}
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metrics.auth.existingSecret.secretName | quote }}
                  key: {{ .Values.metrics.auth.existingSecret.secretKey | quote }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.containerPort | default 9707 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 60
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "bazarr.fullname" . }}-pvc
        {{- else }}
        - name: config
          emptyDir: {}
        {{- end }}
        {{- range $storage := .Values.extraVolumes }}
        - name: {{ $storage.name }}
          persistentVolumeClaim:
            claimName: {{ $storage.pvcName }}
        {{- end }}
        {{- range $configMap := .Values.extraConfigMaps }}
        - name: {{ $configMap.name }}
          configMap:
            name: {{ $configMap.configMapName }}
        {{- end }}
        {{- range $secret := .Values.extraSecrets }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.secretName }}
            items:
              - key: {{ $secret.key }}
                path: {{ $secret.path }}
        {{- end }}
        {{- range $nfsstorage := .Values.nfsVolumes }}
        - name: {{ $nfsstorage.name }}
          nfs:
            server: {{ $nfsstorage.nfs.server }}
            path: {{ $nfsstorage.nfs.path }}
        {{- end }}
        {{- if .Values.config.existingConfigMap }}
        - name: bazarr-temp-config
          configMap:
            name: {{ .Values.config.existingConfigMap }}
            items:
            - key: config.yaml
              path: config.yaml
        {{- end }}
        {{- if .Values.config.existingSecret }}
        - name: bazarr-temp-config
          secret:
            secretName: {{ .Values.config.existingSecret }}
            items:
            - key: config.yaml
              path: config.yaml
        {{- else if (.Values.config.useExternalSecret) }}
        - name: bazarr-temp-config
          secret:
            secretName: {{ include "bazarr.fullname" . }}-config
            items:
            - key: config.yaml
              path: config.yaml
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
